Added new blog post for Matplotlib figures in the IPCC SR15
matplotlib/matplotblog pull request #45
Opened 2021-01-01 10:56 UTC by danielhuppmann

This blog post showcases that Matplotlib was used directly to generate many of the figures in the IPCC Special Report on Global Warming of 1.5°C, as part of a larger effort to increase openness, transparency and reproducibility of the analysis of quantitative scenarios in the report.

**Warning**: I did not manage to get the style of the blog post right without using CSS markings and captions for the figures, so I followed the advice in the [Hugo discussion forum](https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032) and deactivated the feature to ignore raw html. If you don't want to enable this on the entire page, please let me know how to apply the formatting without using raw html tags.

2021-01-04 18:04 UTC, story645 commented
Thanks so much for the contribution!

2021-01-05 15:02 UTC, davidevaleriani requested changes
This is a great post, easy to read and very interesting. Thank you so much for the contribution! Just requesting a minor change and then we publish it.

2021-01-05 15:02 UTC, davidevaleriani commented on content/posts/ipcc-sr15/index.md
> +(doi: [10.1038/s41558-018-0317-4](https://doi.org/)).
The link points to https://doi.org/, while it should point to https://doi.org/10.1038/s41558-018-0317-4

2021-01-05 15:03 UTC, davidevaleriani commented on config.toml
> +unsafe = true
Please add a new line at the end of the config.toml file, and indent the unsafe like category above.

2021-01-05 17:14 UTC, danielhuppmann commented
Thank you @davidevaleriani for the positive response and catching the broken link - I implemented the two requested  changes and double-check that all links work now.

2021-01-05 17:23 UTC, merged